create database EDA;
use EDA;

select * from customers;
select count(*) from products;
select count(*) from sales;

# Explore Structure of database
# Explore all objects in the database

SELECT *
FROM information_schema.tables;


#1 Dimension exploration
#a Explore all the countries our customers come from

Select distinct country
from customers;

#b Explore all the product categories (The major divisions)

SELECT DISTINCT category, subcategory, product_name
FROM products
ORDER BY category, subcategory, product_name;

#3 Dates Exploration
# Explore the earliest and latest dates.
# Understand the scope of data and timespan

#aFind the date of first and last order.

SELECT 
    MIN(order_date) AS first_order_date,
    MAX(order_date) AS last_order_date,
    YEAR(MAX(order_date)) - YEAR(MIN(order_date)) AS year_difference
FROM sales
WHERE YEAR(order_date) <> 0;

#b Find the youngest and eldest customer

select min(birthdate) as eldest_customer,
max(birthdate) as youngest_cutomer
from customers
WHERE YEAR(birthdate) <> 0;

# Calculate age

SELECT
    customer_id,
    birthdate,
    TIMESTAMPDIFF(YEAR, birthdate, CURDATE()) AS age
FROM customers
WHERE YEAR(birthdate) <> 0;

## Measures exploration
# Find the total sales

select sum(sales_amount) as total_sales
from sales;

#B Find how many items are sold

select sum(quantity) as total_sales 
from sales;

#C Find the average selling price

select avg(price) as avg_selling_price
from sales;

#D Find the total number of orders

select count(order_number) as total_no_of_orders , count(distinct order_number) as unique_total_no_of_orders
from sales;

#E Find total number of products
select count(product_key) as total_products
from products;

#F Find total number of customers
 
select count(customer_key) as total_customers
from customers;

#G Find the customers who has placed an order.

select count(distinct customer_key) as placed_order
from sales;

#Report generation
# Generate a report that shows all key metrices of the business
select 'Total_sales' as measure_name, sum(sales_amount) as measure_value
from sales
Union all
select 'Total_Quantity', sum(quantity) 
from sales
Union all
select 'Average_price', Avg(price) as measure_value
from sales
Union all
select 'Total_no_of_products', count(product_key)
from products
union all
select 'Total_no_of_customers', count(customer_key)
from customers
union all
select 'total_no_of_orders', count(distinct order_number)
from sales;

# Magnitude Analysis
# Compare the measures against categories

#a Find total customers by countries
SELECT
    country,
    COUNT(customer_key) AS total_customers
FROM customers
GROUP BY country
ORDER BY total_customers DESC;

#b   Find total customers by gender

select gender,
    COUNT(customer_key) AS total_customers
FROM customers
GROUP BY gender
ORDER BY total_customers DESC;

#c Find total products by category

select category, count(product_key) as total_products
from products
group by category
order by total_products desc;

#d What is the average cost in each category?

Select category, avg(cost) as avg_cost
from products
group by category
order by avg_cost desc;

#e What is the total revenue generated for each category?

select p.category, sum(s.sales_amount) as total_revenue
from sales s
left join products p
on p.product_key= s.product_key
Group by category
order by total_revenue desc;

#f What is the total revenue generated by each customer?

select c.first_name, c.last_name, c.customer_key, sum(s.sales_amount) as total_rev_by_cust
from sales s
left join customers c
on c.customer_key=s.customer_key
group by c.first_name, c.last_name, c.customer_key
order by total_rev_by_cust desc;

#g What is the distribution of sold items across countries?

select c.country, sum(s.quantity) as sold_items
from sales s
left join customers c
on c.customer_key=s.customer_key
group by country
order by sold_items desc;

# Ranking analysis
# TOP AND BOTTOM PERFORMERS

# Which 5 products generate the highest revenue?

SELECT 
    p.product_name,
    SUM(s.sales_amount) AS total_sales
FROM sales s
LEFT JOIN products p
    ON s.product_key = p.product_key
GROUP BY p.product_name
ORDER BY total_sales desc
LIMIT 5;

# Which are the 5 worst performing products?

SELECT 
    p.product_name,
    SUM(s.sales_amount) AS total_sales
FROM sales s
LEFT JOIN products p
    ON s.product_key = p.product_key
GROUP BY p.product_name
ORDER BY total_sales
LIMIT 5;

#################################END###########################

